apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "23"
    field.cattle.io/creatorId: user-94ggc
    field.cattle.io/publicEndpoints: '[{"nodeName":"c-gdfbq:m-13ed94da23fd","addresses":["10.10.3.4"],"port":8383,"protocol":"TCP","podName":"lux4rd0:appdynamics-config-exporter-69f9b754df-q25ww","allNodes":false}]'
  creationTimestamp: "2019-10-01T20:33:40Z"
  generation: 63
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-lux4rd0-appdynamics-config-exporter
  name: appdynamics-config-exporter
  namespace: lux4rd0
  resourceVersion: "961769"
  selfLink: /apis/apps/v1beta2/namespaces/lux4rd0/deployments/appdynamics-config-exporter
  uid: c0ac04de-e48a-11e9-a569-000c295ce9b6
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-lux4rd0-appdynamics-config-exporter
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2019-10-03T18:33:14Z"
        field.cattle.io/ports: '[[{"containerPort":8383,"dnsName":"appdynamics-config-exporter-hostport","hostPort":8383,"kind":"HostPort","name":"8383tcp83830","protocol":"TCP","sourcePort":8383}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-lux4rd0-appdynamics-config-exporter
    spec:
      containers:
      - env:
        - name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
          value: 1b0268fb-3c5e-43b4-af29-1670709f67c2
        - name: APPDYNAMICS_AGENT_ACCOUNT_NAME
          value: customer1
        - name: APPDYNAMICS_AGENT_APPLICATION_NAME
          value: Config-Exporter
        - name: APPDYNAMICS_AGENT_NODE_NAME
          value: Config-Exporter
        - name: APPDYNAMICS_AGENT_TIER_NAME
          value: Config-Exporter
        - name: APPDYNAMICS_ANALYTICS_AGENT_URL
          value: http://pflb01.pulpfree.net:5090/v2/sinks/bt
        - name: APPDYNAMICS_CONTROLLER_HOST_NAME
          value: pfappd02.pulpfree.net
        - name: APPDYNAMICS_CONTROLLER_PORT
          value: "8090"
        - name: APPDYNAMICS_NODE_HISTORICAL
          value: "true"
        - name: APP_PROPERTIES_SERVER_PORT
          value: "8383"
        - name: APP_PROPERTIES_USER_AUTHENTICATION_ENABLED
          value: "false"
        image: pfdocker01.pulpfree.net:5000/lux4rdo/appdynamics-config-exporter:4.5.12.5
        imagePullPolicy: Always
        name: appdynamics-config-exporter
        ports:
        - containerPort: 8383
          hostPort: 8383
          name: 8383tcp83830
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-10-03T15:59:09Z"
    lastUpdateTime: "2019-10-03T15:59:09Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2019-10-01T20:33:28Z"
    lastUpdateTime: "2019-10-03T18:33:10Z"
    message: ReplicaSet "appdynamics-config-exporter-69f9b754df" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 63
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
